### ISSUE TITLE
Open in new window?

### ISSUE THREAD

**Issue by darcyclarke** [richgilbank/Scratch-JS#34]
Thoughts on the option to open the scratchpad in a new tab/window instead of just working out of a devtools tab? May be nice to have the option of using the current devtools tab or hitting a chrome extension bookmark button which would open a new tab.

**Comment by richgilbank** [comment]
@darcyclarke I don't think I understand where the value is here. The project's function right now is to be able to see the es5 output from a transformer, execute in the context of the page being inspected, and simultaneously display the output from `console.log`. That said, I'm down with the idea of serving it up from a URL as well so the output can be logged from there, though again I just don't yet understand the uses for it. Open to ideas on how people might end up using it though; does anything in particular stand out to you as being more useful in a new tab/window?

**Comment by arthurvr** [comment]
I agree with the above comment. I think the tab in devtools is good enough. If you don't want your scripts to execute in the context of the current page, just open `about:blank` lol
