### ISSUE TITLE
Cannot install packaged extension

### ISSUE THREAD

**Issue by LukasPrvy** [richgilbank/Scratch-JS#38]
Install via WebStore fails when trying to unpack extension.

Windows 8.1 64-bit, Chrome 40

**Comment by richgilbank** [comment]
Interesting, thanks for opening the issue...the webstore seemed to be having some issues last night when I uploaded the latest package (I kept getting 500s) - mind trying again now?

**Comment by LukasPrvy** [comment]
Nope, it still doesn't install. I'd love to use this extension though as its an awesome idea. Later I'll look if this isn't some issue on my side, but yesterday I installed another extension and everything was ok.

http://i.imgur.com/dv8lx5I.png

**Comment by richgilbank** [comment]
Strange, I suspect something went sideways during the upload then, maybe it corrupted the package. I've added a new version (0.0.12), which went through without a hitch, so hopefully that will work for you.

**Comment by LukasPrvy** [comment]
Still the same problem, adding another extensions works fine. After some googling it appears that this is a known Chrome regression, that dates back to 2011... Maybe some of these links can become helpful:

http://stackoverflow.com/questions/7984320/chrome-extension-invalid-package-detailscant-unzip-the-extension
http://stackoverflow.com/questions/15259125/developer-chrome-extension-package-is-invalid-details-could-not-uzip-extensi
https://code.google.com/p/chromium/issues/detail?id=402278

**Comment by LukasPrvy** [comment]
Hi! I tried it again and now and it worked like a charm. Thanks a lot for this great extension. Maybe you can consider adding indent width and completions toggle to options and it will be perfect. But that does not apply to this issue at all, you can close it. Thanks for your time.

**Comment by richgilbank** [comment]
Great! I did some work last night to shrink the size (it was recursively building the previous zip file into the new one ಠ_ಠ), so that may have helped as well (14MB -> ~550K). Glad it's working for you. Feel free to create new issues (or submit pull requests!).
