### ISSUE TITLE
Transformers version?

### ISSUE THREAD

**Issue by Pleasurazy** [richgilbank/Scratch-JS#39]
I think transformers should note version, such as CoffeeScript is 1.8 or 1.9?

![chrome_ _-_babel](https://cloud.githubusercontent.com/assets/1500206/6524098/054d642c-c431-11e4-8410-40c88cd549d4.png)

**Comment by richgilbank** [comment]
Great idea - will take a look at this shortly.

**Comment by richgilbank** [comment]
Thanks @Pleasurazy, I've added it in with https://github.com/richgilbank/Scratch-JS/commit/339380d5a8b8c706b38f9f142b7640d4028ea385. Will be publishing v0.0.14 shortly.
