### ISSUE TITLE
Add support of running in context of page iframe

### ISSUE THREAD

**Issue by shytikov** [richgilbank/Scratch-JS#41]
Some people forced to use `iframes` on their pages and for now I don't see a way how to be able easily run JS in context of main's page `iframe`.

Is it possible to add feature of explicitly selecting context on which the script should run?

**Comment by richgilbank** [comment]
Good point. The standard console can be targeted to an iframe, so it would make sense to do the same here. I've started work toward it in the [frame_selector](https://github.com/richgilbank/Scratch-JS/tree/frame_selector) branch and will let you know how it goes. Thanks!
