### ISSUE TITLE
Warn when transformation fails?

### ISSUE THREAD

**Issue by arthurvr** [richgilbank/Scratch-JS#46]
When I make a syntax error, nothing visually happens. Thanks kinda sad as many people will be playing around with ES6 syntax, and want to know it when they do wrong things.

Instead of staying silent I'd suggest to let the user know something, preferably by also indicating the line number, or at least forwarding the error to `console.error()` so they know their script didn't execute.

Really nice tool @richgilbank :+1:!

**Comment by richgilbank** [comment]
It took a while, but this should now be working in master as a result of https://github.com/richgilbank/Scratch-JS/pull/55 - mind trying it out? I'm going to tweak the styles a bit, but otherwise I think it gives good feedback on syntax errors. Thoughts?
Thanks @arthurvr!
