### ISSUE TITLE
Add babel polyfil

### ISSUE THREAD

**Issue by BerkeleyTrue** [richgilbank/Scratch-JS#49]
Ran into an issue trying to play around with iterables.

When you use the spread operator on an iterable babel attempts to use Array.from to convert the iterable but Array.from is only available in the firefox browser. It would be cool if the polyfil was included or be enable-able so that we can play around with these features not yet in modern browsers.

**Comment by zakangelle** [comment]
+1

**Comment by richgilbank** [comment]
@BerkeleyTrue @zakangelle Just taking a look at this now - Could you provide a quick little snippet to test against?

**Comment by BerkeleyTrue** [comment]
Sure

```js
var map = new Map();
map.set('cat', 'foo');

console.log(...map);
```
converts to 
```js
"use strict";

var _toConsumableArray = function (arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) arr2[i] = arr[i]; return arr2; } else { return Array.from(arr); } };

var map = new Map();
map.set("cat", "foo");

console.log.apply(console, _toConsumableArray(map));
```

**Comment by richgilbank** [comment]
@BerkeleyTrue Thanks for this. I have to admit though, I'm not sure I understand the ask. If you're asking to include the [Babel polyfill](http://babeljs.io/docs/usage/polyfill/), it should already be included and working as per [here](https://github.com/richgilbank/Scratch-JS/blob/master/panel/scripts/transformers/babel.js#L6). `Array.from` also seems to be behaving as expected:
```
var m = new Map([[1, 2], [2, 4], [4, 8]]);
console.log(Array.from(m));

// [[1,2],[2,4],[4,8]]
```

Is there another polyfill you're asking to include?

**Comment by BerkeleyTrue** [comment]
It looks like this is working now. I haven't tried using spread no iterables in a long time. Will close this.
