### ISSUE TITLE
Delay loading files until visible

### ISSUE THREAD

**Issue by paulirish** [richgilbank/Scratch-JS#51]
AFAICT you're loading in all the js files as soon as DevTools loads. 

Can you bring them in lazily to not affect the load of the rest?

**Comment by richgilbank** [comment]
Thanks for looking through! 

Absolutely - the vendor bundle is currently up to ~3MB (ouch!), so it makes sense to defer loading of the transformers. 

There’s quite a bit of technical debt in this project, so I’m hoping to take a crack at a hefty refactor shortly.

**Comment by paulirish** [comment]
Sounds cool. Maybe you could use webpack and lazily request the bundle after page visibility API gave you the visible event once the iframe is up.

**Comment by paulirish** [comment]
nice job on this btw

**Comment by richgilbank** [comment]
Hmm - not sure the visibility API is really necessary, as the bundle gets loaded via `panel/repl.html`, which is brought into DevTools through a `chrome.devtools.panels.create` call [here](https://github.com/richgilbank/Scratch-JS/blob/master/es6-repl.js). I was curious as to when the context actually gets constructed so I monitored the DevTools window (broken out of the page):
![](https://s3.amazonaws.com/f.cl.ly/items/2h0g24203L2Y3b350L12/Image%202015-04-12%20at%203.20.19%20PM.png)

So, unless I'm misreading this, I should just be able to lazy load the transformers on window load / after CodeMirror initialization, no?

And thanks!

**Comment by richgilbank** [comment]
Ahh, I think we're talking about 2 different things :P 

I assumed you meant loading the 3MB file was blocking the initial render of the Scratch page - I take it you're concerned about blocking the load of DevTools as a whole? Unless I'm mistaken, it would only slow things down once the user navigates to the Scratch JS tab...or am I just derping?

**Comment by paulirish** [comment]
> Unless I'm mistaken, it would only slow things down once the user navigates to the Scratch JS tab

I wish but i dont think so. 95% sure we call panels.create() as soon as devtools starts.  which triggers all your work in repl.html

### Here's me profiling the refresh of devtools:
#### full view
![image](https://cloud.githubusercontent.com/assets/39191/7107830/f948a066-e126-11e4-9d04-9596b1dddbf3.png)

#### zoomed in and with the context on both sides
![image](https://cloud.githubusercontent.com/assets/39191/7107813/664d0ad6-e126-11e4-8048-81e43527385b.png)

You can see the traceur in the network and then in the execution.

#### steps to do that:
* undock devtools (lets call this one Primary Pete)
* cmd-opt-i to inspect those devtools (lets call this one Secondary Sue)
* in Sue, click to timeline. hit record.
* in Pete go to timeline panel. 
* in pete, hit opt-r. That triggers a refresh of itself (rather than the page it inspects)
* windows will kinda jump around but
* head back to Sue and stop the recording.  you should get a solid profile of it.

**Comment by richgilbank** [comment]
That is strange - with a build from the store, Traceur should never appear on its own currently (it gets usemin-ed into vendor.js). Also, the stack is showing it lives in jspm_packages, but Scratch is all npm. Not to "try turning it off and on again" you, but does it appear when other extensions are disabled as well? I'm suspecting it's being pulled in from somewhere else...

Nice tip with the opt-r! The devtools shimmy™ isn't ideal though - it might be cool to have a context menu with a 'reload this frame' kind of thing for iframes within devtools, or scope the opt-r down to the container context of the element in focus (i.e. scope it down to `$0` would see as `window`). That said, any development flow would probably need livereload or similar anyway, so it would probably be redundant.

**Comment by paulirish** [comment]
Ah. it's true. traceur is coming from @kdzwinel's Emulated Device Lab. :)

**Comment by paulirish** [comment]
gosh it looks like things are good on your extension.

:flushed:

**Comment by richgilbank** [comment]
hah, glad to hear it :sweat_smile: 

Thanks for poking around!
