### ISSUE TITLE
Upgrade babel

### ISSUE THREAD

**Issue by rocketraman** [richgilbank/Scratch-JS#53]
The version of babel distributed in the extension is out of date. For example, the following simple code does not work:

```javascript
this.baz = "123"
let foo = s => s + this.baz
console.log(foo('abc'))
```

results in:

```javascript
"use strict";

undefined.baz = "123";
var foo = function (s) {
  return s + undefined.baz;
};
console.log(foo("abc"));
```

Recent versions of babel correctly assign the `this` reference to the enclosing scope.

**Comment by sebmck** [comment]
No they don't, same behaviour in latest. This is not a bug. See the [FAQ](http://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-).

**Comment by rocketraman** [comment]
You're right. However, that was just a (bad) example. An updated babel would still be nice.
