### ISSUE TITLE
Esc key doesn't open the console the first time

### ISSUE THREAD

**Issue by richgilbank** [richgilbank/Scratch-JS#56]
It seems CodeMirror calls `preventDefault()` on keyboard events, which is preventing them from making their way to devtools' handlers. As a result, when CodeMirror is in focus, hitting `esc` doesn't open the console the first time. Hitting it again, however, will (since it loses focus).

**Comment by dwelle** [comment]
For me when I open the scratch-JS for the first time, even multiple `esc` don't work until I open the console drawer manually via button, then the "hit `esc` twice" works. Dunno what's going on here since it should loose focus either way.

**Comment by richgilbank** [comment]
Not sure what happened (presumably something changed in Chrome itself), but this seems to be working now. ¯\(ツ)/¯
