### ISSUE TITLE
Enable ES7

### ISSUE THREAD

**Issue by dwelle** [richgilbank/Scratch-JS#62]
Enable or allow user to opt-in for experimental (es7) features (for babel).

**Comment by richgilbank** [comment]
@dwelle Babel defaults to stage 2 proposals and up, but I suppose I could include stage 1 as well.

**Comment by richgilbank** [comment]
Added with https://github.com/richgilbank/Scratch-JS/commit/30b663f85ecb524ca58d1a7df47df805ab3a64ab
