### ISSUE TITLE
Option to run plain vanilla JS

### ISSUE THREAD

**Issue by oagarcia** [richgilbank/Scratch-JS#67]
Latest versions of (Chrome i.e Canary) have a good support of ES2015: 82%.

Would be useful if the transpilers can be disabled and run vanilla js... yes the console exists but it is limited in terms of code coloring, multi line formatting, closing brackets, etc, so having ScratchJS as a code/console tester tool for plain JS would be great.

**Comment by abhisekp** [comment]
:+1:

**Comment by oagarcia** [comment]
nice thx!
