### ISSUE TITLE
Add intellisense

### ISSUE THREAD

**Issue by mcshiva** [richgilbank/Scratch-JS#80]
wouldn't that be a cool feature having intellisense like console provides ?
Default Console has awesome feature. As soon as you add DOT to the object it provides all the available properties and functions of that object.

I am sorry if this functionality already exist. help me finding out that :)

**Comment by richgilbank** [comment]
Eek, sorry I didn't respond to this earlier. I'd love for this to exist, and it's precisely what I meant with https://github.com/richgilbank/Scratch-JS/issues/29. I'm going to close this for now, but it would be great for anyone available to dig into what's possible here. Thanks for the reminder @mcshiva!
