### ISSUE TITLE
it's not support the decorator?

### ISSUE THREAD

**Issue by abnerCrack** [richgilbank/Scratch-JS#85]
it's not working in chrome 52.0.2743.41 beta (64-bit)
```
code:

function annotation(target) {
   target.annotated = true;
}

@annotation
class MyClass {
}
console.log(MyClass.annotated)
```

**Comment by richgilbank** [comment]
@abnerCrack It doesn't seem to be working with the [Babel REPL](http://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=function%20annotation(target)%20%7B%0A%20%20%20target.annotated%20%3D%20true%3B%0A%7D%0A%0A%40annotation%0Aclass%20MyClass%20%7B%0A%7D%0Aconsole.log(MyClass.annotated)) either.  
I believe support for decorators were dropped with version 6, as they were moved to an additional plugin while the syntax was being finalized. Related: http://technologyadvice.github.io/es7-decorators-babel6/
